$(document).ready(function() {
    $('#Sven').hover(function(){
        $('#overlay1').show();
        $('#hov1').show();
        $('#txt1').hide();
    })
    $('#Sven').mouseleave(function(){
        $('#hov1').hide();
        $('#overlay1').hide();
        $('#txt1').show();
    })
    $('#Anti-Mage').hover(function(){
        $('#overlay2').show();
        $('#hov2').show();
        $('#txt2').hide();
    })
    $('#Anti-Mage').mouseleave(function(){
        $('#hov2').hide();
        $('#overlay2').hide();
        $('#txt2').show();
    })
    $('#Invoker').hover(function(){
        $('#overlay3').show();
        $('#hov3').show();
        $('#txt3').hide();
    })
    $('#Invoker').mouseleave(function(){
        $('#hov3').hide();
        $('#overlay3').hide();
        $('#txt3').show();
    })
    $('#Pudge').hover(function(){
        $('#overlay4').show();
        $('#hov4').show();
        $('#txt4').hide();
    })
    $('#Pudge').mouseleave(function(){
        $('#hov4').hide();
        $('#overlay4').hide();
        $('#txt4').show();
    })
    $('#Medusa').hover(function(){
        $('#overlay5').show();
        $('#hov5').show();
        $('#txt5').hide();
    })
    $('#Medusa').mouseleave(function(){
        $('#hov5').hide();
        $('#overlay5').hide();
        $('#txt5').show();
    })
    $('#Storm-Spirit').hover(function(){
        $('#overlay6').show();
        $('#hov6').show();
        $('#txt6').hide();
    })
    $('#Storm-Spirit').mouseleave(function(){
        $('#hov6').hide();
        $('#overlay6').hide();
        $('#txt6').show();
    })
    $('#Wraith-King').hover(function(){
        $('#overlay7').show();
        $('#hov7').show();
        $('#txt7').hide();
    })
    $('#Wraith-King').mouseleave(function(){
        $('#hov7').hide();
        $('#overlay7').hide();
        $('#txt7').show();
    })
    $('#Drow-Ranger').hover(function(){
        $('#overlay8').show();
        $('#hov8').show();
        $('#txt8').hide();
    })
    $('#Drow-Ranger').mouseleave(function(){
        $('#hov8').hide();
        $('#overlay8').hide();
        $('#txt8').show();
    })
    $('#Zeus').hover(function(){
        $('#overlay9').show();
        $('#hov9').show();
        $('#txt9').hide();
    })
    $('#Zeus').mouseleave(function(){
        $('#hov9').hide();
        $('#overlay9').hide();
        $('#txt9').show();
    })
})