$(document).ready(function() {
    $('#Sven').hover(function(){
        $('#overlay1').slideDown();
        $('#hov1').slideDown();
        $('#txt1').hide();
    })
    $('#Sven').mouseleave(function(){
        $('#hov1').hide();
        $('#overlay1').hide();
        $('#txt1').fadeIn();
    })
    $('#Anti-Mage').hover(function(){
        $('#overlay2').slideDown();
        $('#hov2').slideDown();
        $('#txt2').hide();
    })
    $('#Anti-Mage').mouseleave(function(){
        $('#hov2').hide();
        $('#overlay2').hide();
        $('#txt2').fadeIn();
    })
    $('#Invoker').hover(function(){
        $('#overlay3').slideDown();
        $('#hov3').slideDown();
        $('#txt3').hide();
    })
    $('#Invoker').mouseleave(function(){
        $('#hov3').hide();
        $('#overlay3').hide();
        $('#txt3').fadeIn();
    })
    $('#Pudge').hover(function(){
        $('#overlay4').slideDown();
        $('#hov4').slideDown();
        $('#txt4').hide();
    })
    $('#Pudge').mouseleave(function(){
        $('#hov4').hide();
        $('#overlay4').hide();
        $('#txt4').fadeIn();
    })
    $('#Medusa').hover(function(){
        $('#overlay5').slideDown();
        $('#hov5').slideDown();
        $('#txt5').hide();
    })
    $('#Medusa').mouseleave(function(){
        $('#hov5').hide();
        $('#overlay5').hide();
        $('#txt5').fadeIn();
    })
    $('#Storm-Spirit').hover(function(){
        $('#overlay6').slideDown();
        $('#hov6').slideDown();
        $('#txt6').hide();
    })
    $('#Storm-Spirit').mouseleave(function(){
        $('#hov6').hide();
        $('#overlay6').hide();
        $('#txt6').fadeIn();
    })
    $('#Wraith-King').hover(function(){
        $('#overlay7').slideDown();
        $('#hov7').slideDown();
        $('#txt7').hide();
    })
    $('#Wraith-King').mouseleave(function(){
        $('#hov7').hide();
        $('#overlay7').hide();
        $('#txt7').fadeIn();
    })
    $('#Drow-Ranger').hover(function(){
        $('#overlay8').slideDown();
        $('#hov8').slideDown();
        $('#txt8').hide();
    })
    $('#Drow-Ranger').mouseleave(function(){
        $('#hov8').hide();
        $('#overlay8').hide();
        $('#txt8').fadeIn();
    })
    $('#Zeus').hover(function(){
        $('#overlay9').slideDown();
        $('#hov9').slideDown();
        $('#txt9').hide();
    })
    $('#Zeus').mouseleave(function(){
        $('#hov9').hide();
        $('#overlay9').hide();
        $('#txt9').show();
    })
})